#!/bin/bash

function stop_radio {
  $(pkill -f "radiotray ") > /dev/null 
}



function start_radio {
  
  RADIO=$(cat $HOME/.radio_stations | grep "$1" | awk {'print $2'}) 
  nohup radiotray $RADIO > /dev/null 2>&1 &

}


function handle_dependencies {
  INSTALLED=$(dpkg -l | grep radiotray | wc -c)

  if (( $INSTALLED == 0)); then
    echo 'Installing radiotray'
    sudo apt-get install radiotray -y
  fi
} 

if [[ $1 == "stop" ]]; then
  stop_radio
  exit
fi



handle_dependencies
stop_radio
start_radio $1
