#!/bin/bash

function stop_radio {
  $(pkill -f "/usr/bin/radiotray") > /dev/null 
}



function start_radio {
  
  RADIO=$(cat $HOME/.radio_stations | grep "$1" | awk {'print $2'}) 
	STATIONS=$(cat $HOME/.radio_stations | awk {'print $1'})
	RADIO_EXIST=$(echo $RADIO | wc -c )

	if (( $RADIO_EXIST == 1 )); then
		notify-send "Try one of these instead:" "$STATIONS"
		exit
	fi

	notify-send --icon=gtk-info -t 1 "Now playing: " $1
  nohup radiotray $RADIO > /dev/null 2>&1 &

}


function handle_dependencies {
  INSTALLED=$(dpkg -l | grep radiotray | wc -c)

  if (( $INSTALLED == 0)); then
    echo 'Installing radiotray'
    sudo apt-get install radiotray -y
  fi
} 

if [[ $1 == "stop" ]]; then
  stop_radio
  exit
fi



handle_dependencies
stop_radio
start_radio $1
